In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('PlayTennis.csv')
data.head()

    Outlook Temperature Humidity    Wind Play Tennis
0     Sunny         Hot     High    Weak          No
1     Sunny         Hot     High  Strong          No
2  Overcast         Hot     High    Weak         Yes
3      Rain        Mild     High    Weak         Yes
4      Rain        Cool   Normal    Weak         Yes

In [4]:
# Problem 1 
# outlook - sunny, Humidity- high, wind - weak
# play or not

In [ ]:
# solution

# p(yes/ sunny,hot,high,weak) = p(sunny/yes) * p(hot/yes) * p(high/yes) * p(weak/yes) * p(yes)

# p(No/ sunny,hot,high,weak) = p(sunny/No) * p(hot/No) * p(high/No) * p(weak/No) * p(No)

#  compare and decinde Maximum a posterior rule

In [7]:
# Problem 2 
# outlook - overcast,temp = cold, Humidity- low, wind - weak
# play or not

In [8]:
# solution

# p(yes/ overcast,cold,high,weak) = p(overcast/yes) * p(cold/yes) * p(high/yes) * p(weak/yes) * p(yes)

# p(No/ overcast,cold,high,weak) = p(overcast/No) * p(cold/No) * p(high/No) * p(weak/No) * p(No)

#  compare and decinde Maximum a posterior rule

In [10]:
# Training

# Lookup table (disctionary)

# Testing

In [11]:
# P(Yes)
# P(No)

In [12]:
data['Play Tennis'].value_counts()

Play Tennis
Yes    9
No     5
Name: count, dtype: int64

In [13]:
py = 9/14
pn = 5/14

In [ ]:
py

0.6428571428571429

In [15]:
pn

0.35714285714285715

In [16]:
# Outlook
pd.crosstab(data['Outlook'],data['Play Tennis'])

Play Tennis  No  Yes
Outlook
Overcast      0    4
Rain          2    3
Sunny         3    2

In [17]:
Pon = 0
Prn = 2/5
Psn = 3/5

Poy = 4/9
Pry = 3/9
Psy = 2/9

In [18]:
# Outlook
pd.crosstab(data['Temperature'],data['Play Tennis'])

Play Tennis  No  Yes
Temperature
Cool          1    3
Hot           2    2
Mild          2    4

In [20]:
PCoolNo = 1/5
PHotNo = 2/5
PMildNo = 2/5

PCoolYes = 3/9
PHotYes = 2/9
PMildYes = 4/9

In [21]:
# Outlook
pd.crosstab(data['Humidity'],data['Play Tennis'])

Play Tennis  No  Yes
Humidity
High          4    3
Normal        1    6

In [22]:
PhighNo = 4/5
Pnormalno = 1/5

Phighyes = 3/9
Pnormalyes = 6/9

In [24]:
# Outlook
pd.crosstab(data['Wind'],data['Play Tennis'])

Play Tennis  No  Yes
Wind
Strong        3    3
Weak          2    6

In [25]:
Pstrongno = 3/5
pweakno = 2/5

Pstrongyes = 3/9
pweakyes = 6/9

In [27]:
# outlook - sunny, Humidity- high, wind - weak

pyes = py*Psy*PHotYes*Phighyes*pweakyes
pyes

0.007054673721340388

In [30]:
# outlook - overcast,temp = cold, Humidity- low, wind - weak
pno = pn*Psn*PHotNo*PhighNo*pweakno
pno

0.02742857142857143

In [31]:
# No Play